create table WorkshopNamePart1 (
	id INT,
	WorkshopName VARCHAR(50)
);
insert into WorkshopNamePart1 (id, WorkshopName) values (1001, 'Innovative bottom-line circuit');
insert into WorkshopNamePart1 (id, WorkshopName) values (1002, 'Multi-tiered holistic encryption');
insert into WorkshopNamePart1 (id, WorkshopName) values (1003, 'Fully-configurable regional synergy');
insert into WorkshopNamePart1 (id, WorkshopName) values (1004, 'Open-architected demand-driven framework');
insert into WorkshopNamePart1 (id, WorkshopName) values (1005, 'Versatile zero administration system engine');
insert into WorkshopNamePart1 (id, WorkshopName) values (1006, 'Optional transitional framework');
insert into WorkshopNamePart1 (id, WorkshopName) values (1007, 'Networked exuding moratorium');
insert into WorkshopNamePart1 (id, WorkshopName) values (1008, 'Up-sized static initiative');
insert into WorkshopNamePart1 (id, WorkshopName) values (1009, 'Compatible discrete moratorium');
insert into WorkshopNamePart1 (id, WorkshopName) values (1010, 'Synergistic 24 hour moratorium');
insert into WorkshopNamePart1 (id, WorkshopName) values (1011, 'Public-key asynchronous focus group');
insert into WorkshopNamePart1 (id, WorkshopName) values (1012, 'Ameliorated fresh-thinking structure');
insert into WorkshopNamePart1 (id, WorkshopName) values (1013, 'Cloned well-modulated installation');
insert into WorkshopNamePart1 (id, WorkshopName) values (1014, 'Assimilated tertiary architecture');
insert into WorkshopNamePart1 (id, WorkshopName) values (1015, 'Operative responsive parallelism');
insert into WorkshopNamePart1 (id, WorkshopName) values (1016, 'Self-enabling logistical knowledge user');
insert into WorkshopNamePart1 (id, WorkshopName) values (1017, 'Distributed contextually-based time-frame');
insert into WorkshopNamePart1 (id, WorkshopName) values (1018, 'Open-source tangible leverage');
insert into WorkshopNamePart1 (id, WorkshopName) values (1019, 'Cloned static help-desk');
insert into WorkshopNamePart1 (id, WorkshopName) values (1020, 'Vision-oriented maximized customer loyalty');
insert into WorkshopNamePart1 (id, WorkshopName) values (1021, 'Exclusive leading edge strategy');
insert into WorkshopNamePart1 (id, WorkshopName) values (1022, 'Front-line logistical approach');
insert into WorkshopNamePart1 (id, WorkshopName) values (1023, 'Innovative 6th generation toolset');
insert into WorkshopNamePart1 (id, WorkshopName) values (1024, 'Total optimal workforce');
insert into WorkshopNamePart1 (id, WorkshopName) values (1025, 'Open-architected uniform service-desk');
insert into WorkshopNamePart1 (id, WorkshopName) values (1026, 'Cross-platform encompassing interface');
insert into WorkshopNamePart1 (id, WorkshopName) values (1027, 'Phased needs-based strategy');
insert into WorkshopNamePart1 (id, WorkshopName) values (1028, 'Re-contextualized user-facing concept');
insert into WorkshopNamePart1 (id, WorkshopName) values (1029, 'Right-sized demand-driven intranet');
insert into WorkshopNamePart1 (id, WorkshopName) values (1030, 'Team-oriented object-oriented implementation');
insert into WorkshopNamePart1 (id, WorkshopName) values (1031, 'Realigned analyzing functionalities');
insert into WorkshopNamePart1 (id, WorkshopName) values (1032, 'Multi-tiered bandwidth-monitored core');
insert into WorkshopNamePart1 (id, WorkshopName) values (1033, 'Virtual asynchronous archive');
insert into WorkshopNamePart1 (id, WorkshopName) values (1034, 'Customer-focused regional pricing structure');
insert into WorkshopNamePart1 (id, WorkshopName) values (1035, 'Advanced object-oriented orchestration');
insert into WorkshopNamePart1 (id, WorkshopName) values (1036, 'Proactive demand-driven synergy');
insert into WorkshopNamePart1 (id, WorkshopName) values (1037, 'Multi-channelled logistical matrix');
insert into WorkshopNamePart1 (id, WorkshopName) values (1038, 'Face to face high-level policy');
insert into WorkshopNamePart1 (id, WorkshopName) values (1039, 'Integrated zero defect capacity');
insert into WorkshopNamePart1 (id, WorkshopName) values (1040, 'Customer-focused client-driven task-force');
insert into WorkshopNamePart1 (id, WorkshopName) values (1041, 'Synchronised uniform approach');
insert into WorkshopNamePart1 (id, WorkshopName) values (1042, 'Extended multimedia analyzer');
insert into WorkshopNamePart1 (id, WorkshopName) values (1043, 'Total responsive groupware');
insert into WorkshopNamePart1 (id, WorkshopName) values (1044, 'Implemented web-enabled artificial intelligence');
insert into WorkshopNamePart1 (id, WorkshopName) values (1045, 'Stand-alone value-added customer loyalty');
insert into WorkshopNamePart1 (id, WorkshopName) values (1046, 'Multi-lateral stable flexibility');
insert into WorkshopNamePart1 (id, WorkshopName) values (1047, 'Implemented global concept');
insert into WorkshopNamePart1 (id, WorkshopName) values (1048, 'Business-focused homogeneous archive');
insert into WorkshopNamePart1 (id, WorkshopName) values (1049, 'Versatile modular contingency');
insert into WorkshopNamePart1 (id, WorkshopName) values (1050, 'Profound optimal success');
insert into WorkshopNamePart1 (id, WorkshopName) values (1051, 'Configurable intangible artificial intelligence');
insert into WorkshopNamePart1 (id, WorkshopName) values (1052, 'Realigned needs-based ability');
insert into WorkshopNamePart1 (id, WorkshopName) values (1053, 'Reverse-engineered composite ability');
insert into WorkshopNamePart1 (id, WorkshopName) values (1054, 'Automated real-time success');
insert into WorkshopNamePart1 (id, WorkshopName) values (1055, 'Upgradable holistic moderator');
insert into WorkshopNamePart1 (id, WorkshopName) values (1056, 'Organic reciprocal superstructure');
insert into WorkshopNamePart1 (id, WorkshopName) values (1057, 'Vision-oriented logistical service-desk');
insert into WorkshopNamePart1 (id, WorkshopName) values (1058, 'Fundamental foreground toolset');
insert into WorkshopNamePart1 (id, WorkshopName) values (1059, 'Reduced 4th generation definition');
insert into WorkshopNamePart1 (id, WorkshopName) values (1060, 'Object-based static instruction set');
insert into WorkshopNamePart1 (id, WorkshopName) values (1061, 'Persevering bifurcated migration');
insert into WorkshopNamePart1 (id, WorkshopName) values (1062, 'Decentralized incremental extranet');
insert into WorkshopNamePart1 (id, WorkshopName) values (1063, 'Decentralized reciprocal moderator');
insert into WorkshopNamePart1 (id, WorkshopName) values (1064, 'Cross-group intangible matrix');
insert into WorkshopNamePart1 (id, WorkshopName) values (1065, 'Robust dedicated encryption');
insert into WorkshopNamePart1 (id, WorkshopName) values (1066, 'Visionary value-added contingency');
insert into WorkshopNamePart1 (id, WorkshopName) values (1067, 'Re-engineered next generation functionalities');
insert into WorkshopNamePart1 (id, WorkshopName) values (1068, 'Organic well-modulated flexibility');
insert into WorkshopNamePart1 (id, WorkshopName) values (1069, 'Grass-roots clear-thinking knowledge user');
insert into WorkshopNamePart1 (id, WorkshopName) values (1070, 'Digitized bifurcated adapter');
insert into WorkshopNamePart1 (id, WorkshopName) values (1071, 'Versatile real-time function');
insert into WorkshopNamePart1 (id, WorkshopName) values (1072, 'Open-architected dynamic product');
insert into WorkshopNamePart1 (id, WorkshopName) values (1073, 'Persevering modular standardization');
insert into WorkshopNamePart1 (id, WorkshopName) values (1074, 'Implemented disintermediate budgetary management');
insert into WorkshopNamePart1 (id, WorkshopName) values (1075, 'Open-source secondary frame');
insert into WorkshopNamePart1 (id, WorkshopName) values (1076, 'Fully-configurable intangible collaboration');
insert into WorkshopNamePart1 (id, WorkshopName) values (1077, 'Robust solution-oriented process improvement');
insert into WorkshopNamePart1 (id, WorkshopName) values (1078, 'Triple-buffered systematic Graphic Interface');
insert into WorkshopNamePart1 (id, WorkshopName) values (1079, 'Cross-group full-range artificial intelligence');
insert into WorkshopNamePart1 (id, WorkshopName) values (1080, 'Customer-focused zero administration projection');
insert into WorkshopNamePart1 (id, WorkshopName) values (1081, 'Centralized holistic analyzer');
insert into WorkshopNamePart1 (id, WorkshopName) values (1082, 'Face to face solution-oriented structure');
insert into WorkshopNamePart1 (id, WorkshopName) values (1083, 'Intuitive homogeneous intranet');
insert into WorkshopNamePart1 (id, WorkshopName) values (1084, 'Configurable actuating structure');
insert into WorkshopNamePart1 (id, WorkshopName) values (1085, 'Open-architected real-time support');
insert into WorkshopNamePart1 (id, WorkshopName) values (1086, 'Intuitive didactic support');
insert into WorkshopNamePart1 (id, WorkshopName) values (1087, 'Multi-channelled human-resource infrastructure');
insert into WorkshopNamePart1 (id, WorkshopName) values (1088, 'Polarised dedicated attitude');
insert into WorkshopNamePart1 (id, WorkshopName) values (1089, 'Polarised zero tolerance open architecture');
insert into WorkshopNamePart1 (id, WorkshopName) values (1090, 'Down-sized motivating definition');
insert into WorkshopNamePart1 (id, WorkshopName) values (1091, 'Persevering 24 hour protocol');
insert into WorkshopNamePart1 (id, WorkshopName) values (1092, 'Progressive cohesive encryption');
insert into WorkshopNamePart1 (id, WorkshopName) values (1093, 'Networked holistic leverage');
insert into WorkshopNamePart1 (id, WorkshopName) values (1094, 'Synchronised user-facing customer loyalty');
insert into WorkshopNamePart1 (id, WorkshopName) values (1095, 'Compatible analyzing open system');
insert into WorkshopNamePart1 (id, WorkshopName) values (1096, 'Virtual non-volatile capacity');
insert into WorkshopNamePart1 (id, WorkshopName) values (1097, 'Adaptive fresh-thinking project');
insert into WorkshopNamePart1 (id, WorkshopName) values (1098, 'Open-architected eco-centric help-desk');
insert into WorkshopNamePart1 (id, WorkshopName) values (1099, 'Sharable analyzing data-warehouse');
insert into WorkshopNamePart1 (id, WorkshopName) values (1100, 'Up-sized systematic interface');
insert into WorkshopNamePart1 (id, WorkshopName) values (1101, 'Proactive human-resource throughput');
insert into WorkshopNamePart1 (id, WorkshopName) values (1102, 'Assimilated global policy');
insert into WorkshopNamePart1 (id, WorkshopName) values (1103, 'Enterprise-wide attitude-oriented product');
insert into WorkshopNamePart1 (id, WorkshopName) values (1104, 'Multi-channelled high-level instruction set');
insert into WorkshopNamePart1 (id, WorkshopName) values (1105, 'Fundamental cohesive service-desk');
insert into WorkshopNamePart1 (id, WorkshopName) values (1106, 'Pre-emptive grid-enabled hub');
insert into WorkshopNamePart1 (id, WorkshopName) values (1107, 'Distributed content-based contingency');
insert into WorkshopNamePart1 (id, WorkshopName) values (1108, 'Fundamental real-time framework');
insert into WorkshopNamePart1 (id, WorkshopName) values (1109, 'Compatible upward-trending extranet');
insert into WorkshopNamePart1 (id, WorkshopName) values (1110, 'Centralized encompassing project');
insert into WorkshopNamePart1 (id, WorkshopName) values (1111, 'Extended intangible circuit');
insert into WorkshopNamePart1 (id, WorkshopName) values (1112, 'Switchable bifurcated Graphical User Interface');
insert into WorkshopNamePart1 (id, WorkshopName) values (1113, 'Compatible intermediate ability');
insert into WorkshopNamePart1 (id, WorkshopName) values (1114, 'Up-sized attitude-oriented matrices');
insert into WorkshopNamePart1 (id, WorkshopName) values (1115, 'Configurable fresh-thinking paradigm');
insert into WorkshopNamePart1 (id, WorkshopName) values (1116, 'Adaptive non-volatile complexity');
insert into WorkshopNamePart1 (id, WorkshopName) values (1117, 'Synchronised directional infrastructure');
insert into WorkshopNamePart1 (id, WorkshopName) values (1118, 'Virtual scalable framework');
insert into WorkshopNamePart1 (id, WorkshopName) values (1119, 'Reverse-engineered 24 hour orchestration');
insert into WorkshopNamePart1 (id, WorkshopName) values (1120, 'Business-focused systematic matrix');
insert into WorkshopNamePart1 (id, WorkshopName) values (1121, 'Fully-configurable multi-tasking knowledge user');
insert into WorkshopNamePart1 (id, WorkshopName) values (1122, 'Up-sized client-driven archive');
insert into WorkshopNamePart1 (id, WorkshopName) values (1123, 'Ergonomic dedicated service-desk');
insert into WorkshopNamePart1 (id, WorkshopName) values (1124, 'Phased exuding adapter');
insert into WorkshopNamePart1 (id, WorkshopName) values (1125, 'Multi-channelled solution-oriented flexibility');
insert into WorkshopNamePart1 (id, WorkshopName) values (1126, 'Triple-buffered heuristic policy');
insert into WorkshopNamePart1 (id, WorkshopName) values (1127, 'Total heuristic complexity');
insert into WorkshopNamePart1 (id, WorkshopName) values (1128, 'Realigned object-oriented groupware');
insert into WorkshopNamePart1 (id, WorkshopName) values (1129, 'Implemented fresh-thinking function');
insert into WorkshopNamePart1 (id, WorkshopName) values (1130, 'Advanced attitude-oriented artificial intelligence');
insert into WorkshopNamePart1 (id, WorkshopName) values (1131, 'Grass-roots coherent artificial intelligence');
insert into WorkshopNamePart1 (id, WorkshopName) values (1132, 'Vision-oriented encompassing database');
insert into WorkshopNamePart1 (id, WorkshopName) values (1133, 'Enhanced real-time time-frame');
insert into WorkshopNamePart1 (id, WorkshopName) values (1134, 'Ameliorated empowering orchestration');
insert into WorkshopNamePart1 (id, WorkshopName) values (1135, 'Extended zero defect capacity');
insert into WorkshopNamePart1 (id, WorkshopName) values (1136, 'Balanced well-modulated forecast');
insert into WorkshopNamePart1 (id, WorkshopName) values (1137, 'Pre-emptive impactful functionalities');
insert into WorkshopNamePart1 (id, WorkshopName) values (1138, 'Reverse-engineered 5th generation open architecture');
insert into WorkshopNamePart1 (id, WorkshopName) values (1139, 'Synergistic interactive strategy');
insert into WorkshopNamePart1 (id, WorkshopName) values (1140, 'Multi-channelled object-oriented paradigm');
insert into WorkshopNamePart1 (id, WorkshopName) values (1141, 'Realigned exuding encoding');
insert into WorkshopNamePart1 (id, WorkshopName) values (1142, 'Organized high-level hardware');
insert into WorkshopNamePart1 (id, WorkshopName) values (1143, 'Front-line executive structure');
insert into WorkshopNamePart1 (id, WorkshopName) values (1144, 'Intuitive multi-state moderator');
insert into WorkshopNamePart1 (id, WorkshopName) values (1145, 'Robust optimal middleware');
insert into WorkshopNamePart1 (id, WorkshopName) values (1146, 'Upgradable directional migration');
insert into WorkshopNamePart1 (id, WorkshopName) values (1147, 'Sharable asynchronous data-warehouse');
insert into WorkshopNamePart1 (id, WorkshopName) values (1148, 'Organic hybrid workforce');
insert into WorkshopNamePart1 (id, WorkshopName) values (1149, 'Public-key dynamic forecast');
insert into WorkshopNamePart1 (id, WorkshopName) values (1150, 'Upgradable methodical time-frame');
insert into WorkshopNamePart1 (id, WorkshopName) values (1151, 'Function-based fault-tolerant focus group');
insert into WorkshopNamePart1 (id, WorkshopName) values (1152, 'Optional multi-tasking emulation');
insert into WorkshopNamePart1 (id, WorkshopName) values (1153, 'User-friendly background solution');
insert into WorkshopNamePart1 (id, WorkshopName) values (1154, 'Cloned mobile analyzer');
insert into WorkshopNamePart1 (id, WorkshopName) values (1155, 'User-friendly eco-centric support');
insert into WorkshopNamePart1 (id, WorkshopName) values (1156, 'Universal web-enabled analyzer');
insert into WorkshopNamePart1 (id, WorkshopName) values (1157, 'Digitized directional knowledge base');
insert into WorkshopNamePart1 (id, WorkshopName) values (1158, 'Versatile system-worthy superstructure');
insert into WorkshopNamePart1 (id, WorkshopName) values (1159, 'Object-based incremental benchmark');
insert into WorkshopNamePart1 (id, WorkshopName) values (1160, 'Stand-alone upward-trending emulation');
insert into WorkshopNamePart1 (id, WorkshopName) values (1161, 'Expanded coherent approach');
insert into WorkshopNamePart1 (id, WorkshopName) values (1162, 'Integrated explicit moratorium');
insert into WorkshopNamePart1 (id, WorkshopName) values (1163, 'Balanced encompassing capability');
insert into WorkshopNamePart1 (id, WorkshopName) values (1164, 'Streamlined local function');
insert into WorkshopNamePart1 (id, WorkshopName) values (1165, 'Extended full-range extranet');
insert into WorkshopNamePart1 (id, WorkshopName) values (1166, 'Triple-buffered mission-critical frame');
insert into WorkshopNamePart1 (id, WorkshopName) values (1167, 'Integrated asynchronous moratorium');
insert into WorkshopNamePart1 (id, WorkshopName) values (1168, 'Polarised next generation extranet');
insert into WorkshopNamePart1 (id, WorkshopName) values (1169, 'Multi-tiered client-server approach');
insert into WorkshopNamePart1 (id, WorkshopName) values (1170, 'Customizable 3rd generation architecture');
insert into WorkshopNamePart1 (id, WorkshopName) values (1171, 'Organized radical open system');
insert into WorkshopNamePart1 (id, WorkshopName) values (1172, 'Multi-lateral modular collaboration');
insert into WorkshopNamePart1 (id, WorkshopName) values (1173, 'Streamlined solution-oriented approach');
insert into WorkshopNamePart1 (id, WorkshopName) values (1174, 'Phased encompassing monitoring');
insert into WorkshopNamePart1 (id, WorkshopName) values (1175, 'Inverse global project');
insert into WorkshopNamePart1 (id, WorkshopName) values (1176, 'Distributed executive monitoring');
insert into WorkshopNamePart1 (id, WorkshopName) values (1177, 'Focused web-enabled intranet');
insert into WorkshopNamePart1 (id, WorkshopName) values (1178, 'Organic system-worthy Graphical User Interface');
insert into WorkshopNamePart1 (id, WorkshopName) values (1179, 'Synchronised optimal conglomeration');
insert into WorkshopNamePart1 (id, WorkshopName) values (1180, 'Ameliorated 4th generation customer loyalty');
insert into WorkshopNamePart1 (id, WorkshopName) values (1181, 'Virtual grid-enabled success');
insert into WorkshopNamePart1 (id, WorkshopName) values (1182, 'Up-sized bottom-line process improvement');
insert into WorkshopNamePart1 (id, WorkshopName) values (1183, 'Persistent demand-driven strategy');
insert into WorkshopNamePart1 (id, WorkshopName) values (1184, 'Virtual regional database');
insert into WorkshopNamePart1 (id, WorkshopName) values (1185, 'Organized client-server forecast');
insert into WorkshopNamePart1 (id, WorkshopName) values (1186, 'Horizontal human-resource database');
insert into WorkshopNamePart1 (id, WorkshopName) values (1187, 'Decentralized background hierarchy');
insert into WorkshopNamePart1 (id, WorkshopName) values (1188, 'Intuitive real-time open architecture');
insert into WorkshopNamePart1 (id, WorkshopName) values (1189, 'Total foreground knowledge base');
insert into WorkshopNamePart1 (id, WorkshopName) values (1190, 'Networked multi-state monitoring');
insert into WorkshopNamePart1 (id, WorkshopName) values (1191, 'Reverse-engineered tertiary utilisation');
insert into WorkshopNamePart1 (id, WorkshopName) values (1192, 'Ameliorated impactful analyzer');
insert into WorkshopNamePart1 (id, WorkshopName) values (1193, 'Configurable cohesive website');
insert into WorkshopNamePart1 (id, WorkshopName) values (1194, 'Configurable client-driven website');
insert into WorkshopNamePart1 (id, WorkshopName) values (1195, 'Progressive zero tolerance approach');
insert into WorkshopNamePart1 (id, WorkshopName) values (1196, 'Compatible regional middleware');
insert into WorkshopNamePart1 (id, WorkshopName) values (1197, 'Realigned non-volatile ability');
insert into WorkshopNamePart1 (id, WorkshopName) values (1198, 'Assimilated national product');
insert into WorkshopNamePart1 (id, WorkshopName) values (1199, 'Progressive zero tolerance support');
insert into WorkshopNamePart1 (id, WorkshopName) values (1200, 'Implemented actuating encoding');
insert into WorkshopNamePart1 (id, WorkshopName) values (1201, 'Distributed upward-trending superstructure');
insert into WorkshopNamePart1 (id, WorkshopName) values (1202, 'Business-focused cohesive database');
insert into WorkshopNamePart1 (id, WorkshopName) values (1203, 'Cloned upward-trending alliance');
insert into WorkshopNamePart1 (id, WorkshopName) values (1204, 'Managed multi-state intranet');
insert into WorkshopNamePart1 (id, WorkshopName) values (1205, 'Multi-channelled zero defect knowledge user');
insert into WorkshopNamePart1 (id, WorkshopName) values (1206, 'Front-line intermediate utilisation');
insert into WorkshopNamePart1 (id, WorkshopName) values (1207, 'Universal impactful structure');
insert into WorkshopNamePart1 (id, WorkshopName) values (1208, 'Proactive next generation alliance');
insert into WorkshopNamePart1 (id, WorkshopName) values (1209, 'User-centric reciprocal model');
insert into WorkshopNamePart1 (id, WorkshopName) values (1210, 'Organized disintermediate capacity');
insert into WorkshopNamePart1 (id, WorkshopName) values (1211, 'Proactive holistic paradigm');
insert into WorkshopNamePart1 (id, WorkshopName) values (1212, 'Up-sized 4th generation secured line');
insert into WorkshopNamePart1 (id, WorkshopName) values (1213, 'Pre-emptive tangible extranet');
insert into WorkshopNamePart1 (id, WorkshopName) values (1214, 'Focused responsive function');
insert into WorkshopNamePart1 (id, WorkshopName) values (1215, 'De-engineered heuristic pricing structure');
insert into WorkshopNamePart1 (id, WorkshopName) values (1216, 'Multi-lateral solution-oriented neural-net');
insert into WorkshopNamePart1 (id, WorkshopName) values (1217, 'Organic didactic synergy');
insert into WorkshopNamePart1 (id, WorkshopName) values (1218, 'Persevering content-based circuit');
insert into WorkshopNamePart1 (id, WorkshopName) values (1219, 'Right-sized exuding product');
insert into WorkshopNamePart1 (id, WorkshopName) values (1220, 'Self-enabling disintermediate monitoring');
insert into WorkshopNamePart1 (id, WorkshopName) values (1221, 'De-engineered non-volatile structure');
insert into WorkshopNamePart1 (id, WorkshopName) values (1222, 'Compatible composite data-warehouse');
insert into WorkshopNamePart1 (id, WorkshopName) values (1223, 'Open-architected 24/7 process improvement');
insert into WorkshopNamePart1 (id, WorkshopName) values (1224, 'Implemented dynamic system engine');
insert into WorkshopNamePart1 (id, WorkshopName) values (1225, 'Organic scalable conglomeration');
insert into WorkshopNamePart1 (id, WorkshopName) values (1226, 'Expanded radical website');
insert into WorkshopNamePart1 (id, WorkshopName) values (1227, 'Face to face methodical framework');
insert into WorkshopNamePart1 (id, WorkshopName) values (1228, 'Virtual 6th generation extranet');
insert into WorkshopNamePart1 (id, WorkshopName) values (1229, 'Reverse-engineered object-oriented artificial intelligence');
insert into WorkshopNamePart1 (id, WorkshopName) values (1230, 'Down-sized heuristic secured line');
insert into WorkshopNamePart1 (id, WorkshopName) values (1231, 'Secured user-facing standardization');
insert into WorkshopNamePart1 (id, WorkshopName) values (1232, 'Front-line secondary website');
insert into WorkshopNamePart1 (id, WorkshopName) values (1233, 'De-engineered even-keeled product');
insert into WorkshopNamePart1 (id, WorkshopName) values (1234, 'Synchronised demand-driven structure');
insert into WorkshopNamePart1 (id, WorkshopName) values (1235, 'Decentralized directional challenge');
insert into WorkshopNamePart1 (id, WorkshopName) values (1236, 'Up-sized coherent collaboration');
insert into WorkshopNamePart1 (id, WorkshopName) values (1237, 'Ergonomic directional toolset');
insert into WorkshopNamePart1 (id, WorkshopName) values (1238, 'Reverse-engineered zero tolerance middleware');
insert into WorkshopNamePart1 (id, WorkshopName) values (1239, 'Devolved optimal analyzer');
insert into WorkshopNamePart1 (id, WorkshopName) values (1240, 'Innovative next generation utilisation');
insert into WorkshopNamePart1 (id, WorkshopName) values (1241, 'Up-sized mobile flexibility');
insert into WorkshopNamePart1 (id, WorkshopName) values (1242, 'Virtual discrete knowledge base');
insert into WorkshopNamePart1 (id, WorkshopName) values (1243, 'User-centric radical architecture');
insert into WorkshopNamePart1 (id, WorkshopName) values (1244, 'Reverse-engineered dedicated paradigm');
insert into WorkshopNamePart1 (id, WorkshopName) values (1245, 'Grass-roots optimal complexity');
insert into WorkshopNamePart1 (id, WorkshopName) values (1246, 'Seamless neutral monitoring');
insert into WorkshopNamePart1 (id, WorkshopName) values (1247, 'Up-sized context-sensitive policy');
insert into WorkshopNamePart1 (id, WorkshopName) values (1248, 'Grass-roots zero administration encryption');
insert into WorkshopNamePart1 (id, WorkshopName) values (1249, 'Optional cohesive strategy');
insert into WorkshopNamePart1 (id, WorkshopName) values (1250, 'Customizable real-time framework');
insert into WorkshopNamePart1 (id, WorkshopName) values (1251, 'Universal non-volatile portal');
insert into WorkshopNamePart1 (id, WorkshopName) values (1252, 'Managed interactive algorithm');
insert into WorkshopNamePart1 (id, WorkshopName) values (1253, 'Switchable clear-thinking access');
insert into WorkshopNamePart1 (id, WorkshopName) values (1254, 'Fundamental hybrid system engine');
insert into WorkshopNamePart1 (id, WorkshopName) values (1255, 'Switchable composite paradigm');
insert into WorkshopNamePart1 (id, WorkshopName) values (1256, 'Implemented solution-oriented policy');
insert into WorkshopNamePart1 (id, WorkshopName) values (1257, 'Public-key national complexity');
insert into WorkshopNamePart1 (id, WorkshopName) values (1258, 'Operative global encoding');
insert into WorkshopNamePart1 (id, WorkshopName) values (1259, 'Advanced multimedia function');
insert into WorkshopNamePart1 (id, WorkshopName) values (1260, 'Secured hybrid superstructure');
insert into WorkshopNamePart1 (id, WorkshopName) values (1261, 'Upgradable system-worthy capacity');
insert into WorkshopNamePart1 (id, WorkshopName) values (1262, 'Distributed mobile orchestration');
insert into WorkshopNamePart1 (id, WorkshopName) values (1263, 'Ameliorated global collaboration');
insert into WorkshopNamePart1 (id, WorkshopName) values (1264, 'Right-sized 6th generation protocol');
insert into WorkshopNamePart1 (id, WorkshopName) values (1265, 'Synergistic cohesive policy');
insert into WorkshopNamePart1 (id, WorkshopName) values (1266, 'Team-oriented bifurcated middleware');
insert into WorkshopNamePart1 (id, WorkshopName) values (1267, 'Face to face zero tolerance data-warehouse');
insert into WorkshopNamePart1 (id, WorkshopName) values (1268, 'Assimilated zero defect productivity');
insert into WorkshopNamePart1 (id, WorkshopName) values (1269, 'Robust needs-based application');
insert into WorkshopNamePart1 (id, WorkshopName) values (1270, 'Fully-configurable methodical hardware');
insert into WorkshopNamePart1 (id, WorkshopName) values (1271, 'Innovative full-range definition');
insert into WorkshopNamePart1 (id, WorkshopName) values (1272, 'Seamless client-server website');
insert into WorkshopNamePart1 (id, WorkshopName) values (1273, 'Profound explicit concept');
insert into WorkshopNamePart1 (id, WorkshopName) values (1274, 'Versatile optimal array');
insert into WorkshopNamePart1 (id, WorkshopName) values (1275, 'Balanced background encryption');
insert into WorkshopNamePart1 (id, WorkshopName) values (1276, 'Polarised client-server extranet');
insert into WorkshopNamePart1 (id, WorkshopName) values (1277, 'Object-based client-server hub');
insert into WorkshopNamePart1 (id, WorkshopName) values (1278, 'Business-focused heuristic framework');
insert into WorkshopNamePart1 (id, WorkshopName) values (1279, 'Multi-lateral attitude-oriented knowledge base');
insert into WorkshopNamePart1 (id, WorkshopName) values (1280, 'Object-based non-volatile orchestration');
insert into WorkshopNamePart1 (id, WorkshopName) values (1281, 'Open-architected empowering benchmark');
insert into WorkshopNamePart1 (id, WorkshopName) values (1282, 'Grass-roots intangible secured line');
insert into WorkshopNamePart1 (id, WorkshopName) values (1283, 'Fundamental impactful instruction set');
insert into WorkshopNamePart1 (id, WorkshopName) values (1284, 'Progressive next generation task-force');
insert into WorkshopNamePart1 (id, WorkshopName) values (1285, 'Stand-alone next generation product');
insert into WorkshopNamePart1 (id, WorkshopName) values (1286, 'Operative value-added product');
insert into WorkshopNamePart1 (id, WorkshopName) values (1287, 'Stand-alone upward-trending secured line');
insert into WorkshopNamePart1 (id, WorkshopName) values (1288, 'Inverse zero tolerance pricing structure');
insert into WorkshopNamePart1 (id, WorkshopName) values (1289, 'Monitored upward-trending initiative');
insert into WorkshopNamePart1 (id, WorkshopName) values (1290, 'Secured systematic hardware');
insert into WorkshopNamePart1 (id, WorkshopName) values (1291, 'Robust tangible process improvement');
insert into WorkshopNamePart1 (id, WorkshopName) values (1292, 'User-friendly fresh-thinking capacity');
insert into WorkshopNamePart1 (id, WorkshopName) values (1293, 'Innovative discrete ability');
insert into WorkshopNamePart1 (id, WorkshopName) values (1294, 'Reverse-engineered empowering orchestration');
insert into WorkshopNamePart1 (id, WorkshopName) values (1295, 'Networked global emulation');
insert into WorkshopNamePart1 (id, WorkshopName) values (1296, 'Triple-buffered maximized intranet');
insert into WorkshopNamePart1 (id, WorkshopName) values (1297, 'Versatile multi-state application');
insert into WorkshopNamePart1 (id, WorkshopName) values (1298, 'Fundamental global superstructure');
insert into WorkshopNamePart1 (id, WorkshopName) values (1299, 'Down-sized bottom-line function');
insert into WorkshopNamePart1 (id, WorkshopName) values (1300, 'Sharable attitude-oriented toolset');
insert into WorkshopNamePart1 (id, WorkshopName) values (1301, 'Up-sized national projection');
insert into WorkshopNamePart1 (id, WorkshopName) values (1302, 'Reactive optimizing functionalities');
insert into WorkshopNamePart1 (id, WorkshopName) values (1303, 'Operative full-range neural-net');
insert into WorkshopNamePart1 (id, WorkshopName) values (1304, 'Re-contextualized discrete website');
insert into WorkshopNamePart1 (id, WorkshopName) values (1305, 'Function-based scalable complexity');
insert into WorkshopNamePart1 (id, WorkshopName) values (1306, 'Optimized empowering support');
insert into WorkshopNamePart1 (id, WorkshopName) values (1307, 'Expanded zero administration matrix');
insert into WorkshopNamePart1 (id, WorkshopName) values (1308, 'Re-engineered systematic Graphical User Interface');
insert into WorkshopNamePart1 (id, WorkshopName) values (1309, 'Profound scalable productivity');
insert into WorkshopNamePart1 (id, WorkshopName) values (1310, 'Distributed tertiary policy');
insert into WorkshopNamePart1 (id, WorkshopName) values (1311, 'Operative upward-trending productivity');
insert into WorkshopNamePart1 (id, WorkshopName) values (1312, 'Realigned regional website');
insert into WorkshopNamePart1 (id, WorkshopName) values (1313, 'Synchronised discrete toolset');
insert into WorkshopNamePart1 (id, WorkshopName) values (1314, 'Triple-buffered 5th generation projection');
insert into WorkshopNamePart1 (id, WorkshopName) values (1315, 'Universal 4th generation extranet');
insert into WorkshopNamePart1 (id, WorkshopName) values (1316, 'Sharable hybrid local area network');
insert into WorkshopNamePart1 (id, WorkshopName) values (1317, 'Reduced upward-trending workforce');
insert into WorkshopNamePart1 (id, WorkshopName) values (1318, 'User-centric uniform installation');
insert into WorkshopNamePart1 (id, WorkshopName) values (1319, 'Object-based bi-directional frame');
insert into WorkshopNamePart1 (id, WorkshopName) values (1320, 'Streamlined 4th generation flexibility');
insert into WorkshopNamePart1 (id, WorkshopName) values (1321, 'Extended interactive software');
insert into WorkshopNamePart1 (id, WorkshopName) values (1322, 'Extended global algorithm');
insert into WorkshopNamePart1 (id, WorkshopName) values (1323, 'Reverse-engineered optimal secured line');
insert into WorkshopNamePart1 (id, WorkshopName) values (1324, 'Customizable dedicated service-desk');
insert into WorkshopNamePart1 (id, WorkshopName) values (1325, 'Expanded national architecture');
insert into WorkshopNamePart1 (id, WorkshopName) values (1326, 'Virtual bandwidth-monitored complexity');
insert into WorkshopNamePart1 (id, WorkshopName) values (1327, 'Grass-roots bandwidth-monitored alliance');
insert into WorkshopNamePart1 (id, WorkshopName) values (1328, 'Object-based grid-enabled paradigm');
insert into WorkshopNamePart1 (id, WorkshopName) values (1329, 'Multi-layered maximized conglomeration');
insert into WorkshopNamePart1 (id, WorkshopName) values (1330, 'Customizable dedicated emulation');
insert into WorkshopNamePart1 (id, WorkshopName) values (1331, 'Assimilated responsive info-mediaries');
insert into WorkshopNamePart1 (id, WorkshopName) values (1332, 'Sharable coherent access');
insert into WorkshopNamePart1 (id, WorkshopName) values (1333, 'Monitored homogeneous approach');
insert into WorkshopNamePart1 (id, WorkshopName) values (1334, 'Digitized coherent support');
insert into WorkshopNamePart1 (id, WorkshopName) values (1335, 'Organic zero administration function');
insert into WorkshopNamePart1 (id, WorkshopName) values (1336, 'Fundamental local intranet');
